version: '3'

services:

    app:
        build:
            context: ./app
            dockerfile: app.dockerfile
        image: 1c23-tp-1-app
        container_name: 1c23-tp-1-app
        networks:
            - tp1_net

    nginx:
        image: nginx:1.23.4
        ports:
            - "5555:80"
        volumes:
            - ./nginx_reverse_proxy.conf:/etc/nginx/conf.d/default.conf:ro
            - ./store/static/files:/static:ro
        networks:
            - tp1_net
        depends_on:
            - app

    graphite:
        image: graphiteapp/graphite-statsd:1.1.10-4
        volumes:
            - ./statsd.config.js:/opt/statsd/config.js
            - ./graphite.storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
        ports:
            - "8090:80"
            - "8125:8125/udp"
            - "8126:8126"

    grafana:
        image: grafana/grafana:9.2.15
        ports:
            - "10080:3000"
        volumes:
            - "grafana_config:/var/lib/grafana"

    cadvisor:
        image: gcr.io/cadvisor/cadvisor:v0.47.0
        networks:
            - tp1_net
        depends_on:
            - graphite
        command: -storage_driver="statsd" -storage_driver_host="graphite:8125" -storage_driver_db="cadvisor" -storage_driver_buffer_duration="1s"
        ports:
            - "8080:8080"
        volumes:
            - "/:/rootfs:ro"
            - "/var/run:/var/run:rw"
            - "/sys:/sys:ro"
            - "/var/lib/docker/:/var/lib/docker:ro"

volumes:
    grafana_config:
        driver: local

networks:
    tp1_net:
