version: '3'

services:

    redis:
        image: redis:latest
        networks:
            - tp1_net

    app_1:
        build:
            context: ./app
            dockerfile: app.dockerfile
        image: 1c23-tp-1-app
        container_name: 1c23-tp-1-app-1
        networks:
            - tp1_net

    app_2:
        build:
            context: ./app
            dockerfile: app.dockerfile
        image: 1c23-tp-1-app
        container_name: 1c23-tp-1-app-2
        networks:
            - tp1_net

    app_3:
        build:
            context: ./app
            dockerfile: app.dockerfile
        image: 1c23-tp-1-app
        container_name: 1c23-tp-1-app-3
        networks:
            - tp1_net
    
    nginx:
        image: nginx:1.23.4
        ports:
            - "5555:80"
        volumes:
            - ./nginx_reverse_proxy.conf:/etc/nginx/conf.d/default.conf:ro
            - ./store/static/files:/static:ro
        networks:
            - tp1_net
        depends_on:
            - app_1
            - app_2
            - app_3

    graphite:
        image: graphiteapp/graphite-statsd:1.1.10-4
        ports:
            - "8090:80"
            - "8125:8125/udp"
            - "8126:8126"
        volumes:
            - ./statsd.config.js:/opt/statsd/config.js
            - ./graphite.storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
        networks:
            - tp1_net

    grafana:
        image: grafana/grafana:9.2.15
        ports:
            - "8081:3000"
        volumes:
            - "grafana_config:/var/lib/grafana"

volumes:
    grafana_config:
        driver: local

networks:
    tp1_net:
